services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_CONNECT_TIMEOUT=5000
      - REDIS_TLS=0
      - PRIVATE_KEY="TEST_KEY"
    ports:
      - "3000:3000"
    depends_on:
      - redis
  redis:
    image: redis
    ports:
      - "6379:6379"
